version: "1.0.0"
services:
  postgresql:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=actix
    ports:
      - "5432:5432"
